runtime: go122

env: standard
instance_class: F1
handlers:
  - url: '/api/v1/.*'
    script: auto

  - url: '/assets/(.*)'
    static_files: "dist/assets/\\1"
    require_matching_file: false
    upload: 'dist/assets/(.*)'

  - url: '/'
    static_files: dist/index.html
    require_matching_file: false
    upload: dist/index.html

env_variables:
  ORIGIN_ALLOWED: "<YOUR_CROS_DOMAIN_URL>" # you need to change it, like https://xxx.xxx.xxx
  BUCKET_NAME: "<YOUR_BUCKET_NAME>"

service_account: <YOUR_SERVICE_ACCOUNT>
